### ISSUE TITLE
oracle数据库不能生成文档

### ISSUE THREAD

**Issue by wangzai9999** [vran-dev/databasir#149]
oracle数据库配置成功后，生成文档报错
![1651807872(1)](https://user-images.githubusercontent.com/43926391/167062872-ce430cda-7ac7-4881-a55a-7ee29ff00a05.png)

`Exception in thread "projectSyncTaskThreadPoolTaskExecutor-19" com.databasir.common.DatabasirException: 获取数据库信息失败
	at com.databasir.core.domain.DomainErrors.exception(DomainErrors.java:55)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.databasir.core.domain.document.service.DocumentService.retrieveDatabaseMeta(DocumentService.java:145)
	at com.databasir.core.domain.document.service.DocumentService.syncByProjectId(DocumentService.java:94)
	at com.databasir.core.domain.document.service.DocumentService$$FastClassBySpringCGLIB$$122722d1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.databasir.core.domain.document.service.DocumentService$$EnhancerBySpringCGLIB$$5a47723c.syncByProjectId(<generated>)
	at com.databasir.job.ProjectSyncTaskScheduler.sync(ProjectSyncTaskScheduler.java:53)
	at com.databasir.job.ProjectSyncTaskScheduler.lambda$startSyncTask$0(ProjectSyncTaskScheduler.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by vran-dev** [comment]
@wangzai9999  确认 db 中存在指定的 schema 吗？

**Comment by wangzai9999** [comment]
是存在的，但是大小写不一样，oracle是大写的，但是小写可以链接成功，不能同步，试了下大写，是可以同步成功的

**Comment by vran-dev** [comment]
这应该是不同的数据库在连接时校验规则不一样，oracle 可能在连接的时候不做 schema 的校验

**Comment by wangzai9999** [comment]
oracle生成的文档没有注释（数据库字段添加了注释），这个是要手动配置吗?mysql可以

**Comment by vran-dev** [comment]
> oracle生成的文档没有注释（数据库字段添加了注释），这个是要手动配置吗?mysql可以

连接加一个属性 `remarksReporting=true` 试试

**Comment by vran-dev** [comment]
https://doc.databasir.com/#/README

@wangzai9999  如果你还有任何问题，欢迎通过上面的连接加群讨论
