### ISSUE TITLE
docker-compose can not runing on Mac

### ISSUE THREAD

**Issue by tianlu1677** [vran-dev/databasir#264]
在文档中有一处错误
```ruby
# https://doc.databasir.com/

environment:
      DATABASIR_DB_URL: mysql:3306
      DATABASIR_DB_USERNAME: root # this line
      DATABASIR_DB_PASSWORD: 123456
```
启动之后, mysql 运行正常

```sh
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                   PORTS                               NAMES
ed443b5cfc1f   mysql:8.0.29   "docker-entrypoint.s…"   10 minutes ago   Up 8 minutes (healthy)   0.0.0.0:3306->3306/tcp, 33060/tcp   databasir-mysql-1
```

但是container无法启动

```
lException:
databasir-databasir-1  | Unable to obtain connection from database: null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  | -----------------------------------------------------------------------------------------------------------------------------------------
databasir-databasir-1  | SQL State  : HY000
databasir-databasir-1  | Error Code : 1130
databasir-databasir-1  | Message    : null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  |
databasir-databasir-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	... 62 common frames omitted
databasir-databasir-1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDao': Unsatisfied dependency expressed through field 'dslContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException:
databasir-databasir-1  | Unable to obtain connection from database: null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  | -----------------------------------------------------------------------------------------------------------------------------------------
databasir-databasir-1  | SQL State  : HY000
databasir-databasir-1  | Error Code : 1130
databasir-databasir-1  | Message    : null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  |
databasir-databasir-1  | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	... 76 common frames omitted
databasir-databasir-1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException:
databasir-databasir-1  | Unable to obtain connection from database: null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  | -----------------------------------------------------------------------------------------------------------------------------------------
databasir-databasir-1  | SQL State  : HY000
databasir-databasir-1  | Error Code : 1130
databasir-databasir-1  | Message    : null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  |
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	... 91 common frames omitted
databasir-databasir-1  | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException:
databasir-databasir-1  | Unable to obtain connection from database: null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  | -----------------------------------------------------------------------------------------------------------------------------------------
databasir-databasir-1  | SQL State  : HY000
databasir-databasir-1  | Error Code : 1130
databasir-databasir-1  | Message    : null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  |
databasir-databasir-1  | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:68) ~[flyway-core-7.7.3.jar!/:na]
databasir-databasir-1  | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69) ~[flyway-core-7.7.3.jar!/:na]
databasir-databasir-1  | 	at org.flywaydb.core.Flyway.execute(Flyway.java:508) ~[flyway-core-7.7.3.jar!/:na]
databasir-databasir-1  | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:165) ~[flyway-core-7.7.3.jar!/:na]
databasir-databasir-1  | 	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.5.11.jar!/:2.5.11]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.17.jar!/:5.3.17]
databasir-databasir-1  | 	... 103 common frames omitted
databasir-databasir-1  | Caused by: java.sql.SQLException: null,  message from server: "Host '172.21.0.3' is not allowed to connect to this MySQL server"
databasir-databasir-1  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
databasir-databasir-1  | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
databasir-databasir-1  | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
databasir-databasir-1  | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
databasir-databasir-1  | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
databasir-databasir-1  | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
databasir-databasir-1  | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:na]
databasir-databasir-1  | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:54) ~[flyway-core-7.7.3.jar!/:na]
databasir-databasir-1  | 	... 109 common frames omitted
databasir-databasir-1  |
databasir-databasir-1 exited with code 1
```

**Comment by vran-dev** [comment]
谢谢，文档已修正
